import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ui/mode-toggle";
import LeftBar from "@/components/left-bar";
import RightBar from "@/components/right-bar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background antialiased`}
      >
        <ThemeProvider
          attribute="class"
          disableTransitionOnChange={true}
          defaultTheme="light"
        >
          <div className={"flex flex-row h-full justify-center"}>
            <div
              className={
                "w-full sticky flex h-fit items-start top-0 justify-end"
              }
            >
              <LeftBar />
            </div>
            <div className={"w-full"}>{children}</div>
            <div
              className={
                "w-full sticky flex h-fit items-start top-0 justify-start"
              }
            >
              <RightBar />
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
